version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Backend port
      - "80:80"      # Frontend port
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN}  # Pass GitHub token from host
    volumes:
      - ./deploy-flow-backend/.env:/app/backend/.env  # Mount .env file for backend
    restart: unless-stopped
